### ISSUE TITLE
session.follow_by_tags ~user is inaccessible

### ISSUE THREAD

**Issue by RainbowTob** [InstaPy/InstaPy#6205] opened 2021-06-01 14:54 UTC
## Expected Behavior
No error message, follow by tag detected
## Current Behavior

WARNING [2021-06-01 16:39:07] [XXXXX]  --> Couldn't follow 'XXX'!	~user is inaccessible

Same problem as before with "like by tags" (which has already been fixed)

user followed anyway, but no ID Tracking.

**Comment by schealex** [comment] 2021-06-02 11:26
duplicate of #6200 and fixed by #6204

**Comment by RainbowTob** [comment] 2021-06-02 12:34
It was fixed, but the problem has come back! :(

**Comment by RainbowTob** [comment] 2021-06-02 15:58
During Session abort. I get this message:

Traceback (most recent call last):
  File "C:\Users\XXXX\Desktop\Instapy\V1.py", line 68, in <module>
    session.like_by_tags(like_tags, amount=random.randint(9, 13))
  File "C:\Users\XXXX\AppData\Local\Programs\Python\Python39\lib\site-packages\instapy\instapy.py", line 2081, in like_by_tags
    follow_state, msg = follow_user(
  File "C:\Users\XXXX\AppData\Local\Programs\Python\Python39\lib\site-packages\instapy\unfollow_util.py", line 557, in follow_user
    follow_state, msg = verify_action(
  File "C:\Users\XXXX\AppData\Local\Programs\Python\Python39\lib\site-packages\instapy\unfollow_util.py", line 1560, in verify_action
    button.click()
  File "C:\Users\XXXX\AppData\Local\Programs\Python\Python39\lib\site-packages\selenium\webdriver\remote\webelement.py", line 80, in click
    self._execute(Command.CLICK_ELEMENT)
  File "C:\Users\XXXX\AppData\Local\Programs\Python\Python39\lib\site-packages\selenium\webdriver\remote\webelement.py", line 633, in _execute
    return self._parent.execute(command, params)
  File "C:\Users\XXXX\AppData\Local\Programs\Python\Python39\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "C:\Users\XXXX\AppData\Local\Programs\Python\Python39\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.ElementClickInterceptedException: Message: Element <button class="_5f5mN       jIbKX  _6VtSN      _3yx3p  "> is not clickable at point (225,128) because another element <div class="dxxpA  HjTD7  "> obscures it

**Closed as completed** 2021-06-03 13:07 UTC
