### ISSUE TITLE
Headless Chrome doesn't work anymore ?

### ISSUE THREAD

**Issue by someralex** [InstaPy/InstaPy#4401] opened 2019-05-07 16:31 UTC
Hello.
Before 00:00 - 7 May 2019 - everything work fine .

Seems like today headless Chrome browser not working anymore. 

## Expected Behavior

Like image

## Current Behavior

--> Image was not able to get Liked! maybe blocked ?

## InstaPy configuration

session = InstaPy(username=insta_username,
                  password=insta_password,
                  headless_browser=True,
                  disable_image_load=True)

if headless_browser set to False - everything work 

As i can see in logs - It's issue started today at 00:00 . I am not blocked in IG (iOS app from the same IP and LTE works fine) . And :

headless_browser = False 

works fine

Seems like the same situation with :

follow user followers
unfollow

=====
will try with different settings

**Comment by InfraRedApple** [comment] 2019-05-07 19:06
I am unable to get the users followers list. All return 0.

**Comment by aneopsy** [comment] 2019-05-07 21:55
I confirm, I have the same issue.

**Comment by jeromefaria** [comment] 2019-05-07 23:07
Same here, even after updating through pip. 

Possibly duplicate of #4393?

**Comment by jeromefaria** [comment] 2019-05-08 09:03
[Temporary solution](https://github.com/timgrossmann/InstaPy/issues/4359#issuecomment-488350711) by downgrading Chrome.

**Comment by dopa1213** [comment] 2019-06-09 11:30
Same here

**Closed as completed** 2019-07-16 12:36 UTC
Labels: wontfix
