### ISSUE TITLE
Unfollow not respecting my restrictions.

### ISSUE THREAD

**Issue by raulafrosa** [InstaPy/InstaPy#224] opened 2017-05-03 16:43 UTC
Hi,

First I want to congratulate you for the program, it's very good.

I'm having a issue whem unfollow persons, I have found the problem but I can't fix.
The problem is that my person_list in unfollow_util.py is creating a list of the same name repeated.
When the program do the if for not unfollow people in dont_include as person_list is a list of the same name, if the name is not in dont_include the program will unfollow all peolple until reach 10 people.

I expect that I could inform my problem, if there is any question please ask me =)

**Comment by timgrossmann** [comment] 2017-05-03 18:32
@raulrosa89 Thank you!

Thank you for that bug, we'll fix that ASAP!

**Comment by wordythebyrd** [comment] 2017-05-06 03:31
@timgrossmann 

The issue is here: https://github.com/timgrossmann/InstaPy/blob/master/instapy/unfollow_util.py#L20

```
  person_list = person_list_div.find_elements_by_class_name('_cx1ua')

  person_list = [x.find_element_by_xpath('//div[@class="_gzjax"]/a').text for x in person_list]
```

This returns an array of the first name over and over.  I fixed this locally by grabbing the a tags in the first find_elements_by_class_name.

```
  person_list = person_list_div.find_elements_by_class_name('_4zhc5')
  person_list = [(x.text) for x in person_list]
```

**Comment by wordythebyrd** [comment] 2017-05-06 03:38
Another issue is if you end up with the last 10 users you followed in the dont_include list, you get stuck in an infinite loop.  

A suggestion for this would be to set the followingCount before loading the modal, then divide that number by 10 (the number of users displayed at a time), then send key Key.END once per every 10 following users to load them all in, then grab the li's

**Comment by timgrossmann** [comment] 2017-05-06 07:46
@wordythebyrd could you submit a PR to fix this?
Please use `find_element_by_xpath()` for more stable results

Yes, the infinite loop also is a problem. It is known, but not as important as other stuff right now. But feel free to make a PR with the mentioned changes! Would be glad to have more colllaborators! 

Thanky you

**Comment by converge** [comment] 2017-11-20 00:21
hey guys, just checked, all these bugs are gone. closing it.

**Closed as completed by converge** 2017-11-20 00:21 UTC
Labels: bug, enhancement
