### ISSUE TITLE
Timeout

### ISSUE THREAD

**Issue by anagrou** [InstaPy/InstaPy#5465] opened 2020-05-07 13:29 UTC
## Current Behavior
= RESTART: C:\Users\agrou\Desktop\instapy-quickstart-master\basic_follow-unfollow_activity.py
InstaPy Version: 0.6.8
 ._.  ._.  ._.  ._.  ._.  ._.  ._.  ._.  ._. 
Workspace in use: "C:/Users/agrou/InstaPy"
OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO
INFO [2020-05-07 14:19:08] [anasofiagrou]  Session started!
oooooooooooooooooooooooooooooooooooooooooooooooooooooo
INFO [2020-05-07 14:19:08] [anasofiagrou]  -- Connection Checklist [1/3] (Internet Connection Status)
INFO [2020-05-07 14:19:09] [anasofiagrou]  - Internet Connection Status: ok
INFO [2020-05-07 14:19:09] [anasofiagrou]  - Current IP is "77.54.116.71" and it's from "Portugal/PT"
INFO [2020-05-07 14:19:09] [anasofiagrou]  -- Connection Checklist [2/3] (Instagram Server Status)
INFO [2020-05-07 14:19:17] [anasofiagrou]  - Instagram WebSite Status: Currently Up 
INFO [2020-05-07 14:19:17] [anasofiagrou]  - Instagram Response Time: 141.389 ms 
INFO [2020-05-07 14:19:17] [anasofiagrou]  - Instagram Reponse Code: 200
INFO [2020-05-07 14:19:17] [anasofiagrou]  - Instagram Server Status: ok
INFO [2020-05-07 14:19:17] [anasofiagrou]  -- Connection Checklist [3/3] (Hide Selenium Extension)
INFO [2020-05-07 14:19:17] [anasofiagrou]  - window.navigator.webdriver response: False
INFO [2020-05-07 14:19:17] [anasofiagrou]  - Hide Selenium Extension: ok
..................................................................
INFO [2020-05-07 14:19:29] [anasofiagrou]  Logged in successfully!
''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''
INFO [2020-05-07 14:19:29] [anasofiagrou]  Saving account progress...
________________________________________________________________________________
INFO [2020-05-07 14:19:44] [anasofiagrou]  Starting to follow user `Followers`..
""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
INFO [2020-05-07 14:19:44] [anasofiagrou]  User 'biscaiapro' [1/2]

INFO [2020-05-07 14:25:03] [anasofiagrou]  Sessional Live Report:
	|> No any statistics to show

[Session lasted 6.06 minutes]
OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO
INFO [2020-05-07 14:25:03] [anasofiagrou]  Session ended!
ooooooooooooooooooooooooooooooooooooooooooooooooooooooooo

Traceback (most recent call last):
  File "C:\Users\agrou\Desktop\instapy-quickstart-master\basic_follow-unfollow_activity.py", line 61, in <module>
    session.follow_user_followers(['biscaiapro', 'bptowers_ifbbpro'], amount=100,
  File "C:\Users\agrou\AppData\Local\Programs\Python\Python38-32\lib\site-packages\instapy\instapy.py", line 3454, in follow_user_followers
    person_list, simulated_list = get_given_user_followers(
  File "C:\Users\agrou\AppData\Local\Programs\Python\Python38-32\lib\site-packages\instapy\unfollow_util.py", line 1013, in get_given_user_followers
    person_list, simulated_list = get_users_through_dialog_with_graphql(
  File "C:\Users\agrou\AppData\Local\Programs\Python\Python38-32\lib\site-packages\instapy\unfollow_util.py", line 767, in get_users_through_dialog_with_graphql
    browser.get("view-source:{}".format(url))
  File "C:\Users\agrou\AppData\Local\Programs\Python\Python38-32\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 333, in get
    self.execute(Command.GET, {'url': url})
  File "C:\Users\agrou\AppData\Local\Programs\Python\Python38-32\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "C:\Users\agrou\AppData\Local\Programs\Python\Python38-32\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message: Timeout loading page after 300000ms

## InstaPy configuration

So .. after reading the previous problems, I already downgraded the firefox and added a line on the brower.py but still can't run... any idea?

**Comment by finedesignz** [comment] 2020-05-07 20:26
Duplicate of #5461

**Closed as completed** 2020-05-11 08:34 UTC
