### ISSUE TITLE
UnicodeEncodeError

### ISSUE THREAD

**Issue by iRajul** [InstaPy/InstaPy#51] opened 2017-04-08 06:23 UTC
Traceback (most recent call last):
  File "quickstart.py", line 7, in <module>
    .like_by_tags(['#jainism', '#jain', '#jainsmo'], amount=100)\
  File "C:\Users\user\Documents\insta\InstaPy\instapy\instapy.py", line 224, in like_by_tags
    self.ignore_if_contains, self.username)
  File "C:\Users\user\Documents\insta\InstaPy\instapy\like_util.py", line 67, in check_link
print('Description: ' + image_text)
File "C:\Python27\lib\encodings\cp437.py", line 12, in encode
    return codecs.charmap_encode(input,errors,encoding_map)
UnicodeEncodeError: 'charmap' codec can't encode character u'\u0131' in position
 44: character maps to <undefined>

**Comment by timgrossmann** [comment] 2017-04-08 07:00
@iRajul Please first look through the issues...
Duplicate of #45

**Closed as completed by timgrossmann** 2017-04-08 07:00 UTC
