### ISSUE TITLE
What does "percentage" means?

### ISSUE THREAD

**Issue by arypurnomoz** [InstaPy/InstaPy#1290] opened 2018-01-27 03:42 UTC
Sorry for the stupid question, but i'm still not clear by what does the "percentage" arguments really means.

Perhaps it would be better if there is some explanation about it on the docs..

Once more, sorry for the stupid question

**Comment by ganeshkrishnan1** [comment] 2018-01-27 10:22
session.set_do_comment(True, percentage=80)

Of all the activities (likes) the bot will comment on 80% of the images. The percentage is in a set field and that field action will be done that percentage times. 1% means out of 100 likes, the bot will comment on one photo.

This is not an issue. Please close it to keep the list clean

**Comment by luigifaticoso** [comment] 2018-01-28 22:14
If the problem is solved, you can close the issue

**Closed as completed** 2018-11-23 08:06 UTC
Labels: wontfix
