### ISSUE TITLE
KeyError: 0

### ISSUE THREAD

**Issue by wyrw** [InstaPy/InstaPy#6463] opened 2022-01-20 08:40 UTC
Hi, I have problem for 14h now,   I have update to InstaPy Version: 0.6.16 but it doesnt help. 
Instagram probably changed the position of the button in the code, can you help?

the last lines of code I get:
File "C:\Users\..\AppData\Local\Programs\Python\Python310\lib\site-packages\instapy\instapy.py", line 1980, in like_by_tags
    inappropriate, user_name, is_video, reason, scope = check_link(
  File "C:\Users\..\AppData\Local\Programs\Python\Python310\lib\site-packages\instapy\like_util.py", line 619, in check_link
    media = post_page[0]["shortcode_media"]
KeyError: 0

**Comment by eXtraMt** [comment] 2022-01-20 11:18
facing the same problem

**Comment by vzhyvov** [comment] 2022-01-20 11:20
The same

**Comment by Goli777** [comment] 2022-01-20 12:19
Same https://github.com/InstaPy/InstaPy/issues/6462

**Comment by alexpzpz** [comment] 2022-01-20 12:48
Same problem, likes don't work
did you create a thread first? then began to translate other topics (
my  #6464

**Comment by limberger** [comment] 2022-01-20 14:20
same #6462

**Comment by limberger** [comment] 2022-01-20 14:23
Duplicate of #6462

**Comment by wyrw** [comment] 2022-01-20 16:11
ok so #6462 #6463 and #6464 are facing the same problem, delete this one?

**Closed as completed** 2022-01-20 17:00 UTC
