### ISSUE TITLE
Script trying to like less images than specified

### ISSUE THREAD

**Issue by SamuelMTDavies** [InstaPy/InstaPy#220] opened 2017-05-02 19:43 UTC
I keep setting my script to like say 100 images of 3 different hashtags.

However sometimes when I get to the second, third or fourth hashtag (doesn't seem to be the same one) it only tries to like say 32 images.

Am I correct in thinking that the following code

`.like_by_tags(like, amount=100)`

should attempt to like 100 of each hashtag in my like variable list? Has anyone else come across this?

I don't have a screenshot but I will update with one next time it happens

Thanks for the help.

Sam

**Comment by pekapa** [comment] 2017-05-02 19:55
Duplicate of #204

**Comment by SamuelMTDavies** [comment] 2017-05-02 19:58
Apologies

I did do a search but obviously not very well.

**Closed as completed** 2017-05-02 20:27 UTC
