### ISSUE TITLE
Unfollow stopped working. " 'NoneType' object is not subscriptable"

### ISSUE THREAD

**Issue by alxhoff** [InstaPy/InstaPy#1879] opened 2018-04-18 14:03 UTC
## Expected Behavior
Unfollow onlyNotFollowMe is True and onlyInstapyFollowed is False.
## Current Behavior
Throwing error 
```
unable to get followers and following information 
 'NoneType' object is not subscriptable

```

## Possible Solution (optional)
I pulled master yesterday, I think it was wheb this behavior started
## InstaPy configuration

> session.unfollow_users(amount=tmp_unfollow_amount, onlyNotFollowMe = True,                       unfollow_after=72*60*60, sleep_delay=randint(10,13) * 60)

Any help appreciated.

Cheers

**Comment by flothousand** [comment] 2018-04-18 16:16
Have the same issue :)

**Comment by timmoh** [comment] 2018-04-18 21:03
Duplicate of #1878

**Comment by holymolly** [comment] 2018-04-19 00:49
same here

**Closed as completed** 2018-04-20 18:59 UTC
