### ISSUE TITLE
Not following and crashing when the nickname is too long

### ISSUE THREAD

**Issue by luigifaticoso** [InstaPy/InstaPy#1213] opened 2018-01-10 13:24 UTC
## Expected Behavior
Follow the user with a very long nickname: vavendomeaoyama_yurakuchomarui (this long)
## Current Behavior
Didn't follow the user
``` File "/Library/Python/2.7/site-packages/selenium-2.53.6-py2.7.egg/selenium/webdriver/remote/errorhandler.py", line 192, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.ElementNotVisibleException: Message: element not visible
  (Session info: chrome=63.0.3239.132)
  (Driver info: chromedriver=2.34.522932 (4140ab217e1ca1bec0c4b4d1b148f3361eb3a03e),platform=Mac OS X 10.13.2 x86_64)
```

## Possible Solution (optional)
To skip user with nicknames too long

**Comment by uni1783** [comment] 2018-01-11 10:14
Duplicate of this bug? https://github.com/timgrossmann/InstaPy/issues/1025

**Comment by luigifaticoso** [comment] 2018-01-15 14:06
yep closing it

**Closed as completed** 2018-01-15 14:06 UTC
