### ISSUE TITLE
Instapy is not unfollowing users without photos

### ISSUE THREAD

**Issue by zubus** [InstaPy/InstaPy#5675] opened 2020-07-30 16:01 UTC
**Expected Behavior**

When I run Instapy to unfollow users by not followers or a custom list, the script skips the accounts without any uploaded photos

## Current Behavior

For example, this script (users without uploaded photos):

```
custom_list = ["user1", "user2", "etc"]

session.unfollow_users(amount=3, custom_list_enabled=True, custom_list=custom_list, custom_list_param="all", style="FIFO", unfollow_after=55*60*60, sleep_delay=623)
```

Generate this log:

`Ongoing Unfollow [1/3]: now unfollowing 'b'user1''...
INFO [2020-07-30 11:42:49] [xxxx]  --> Already unfollowed 'user1'! or a private user that rejected your req`

## Possible Solution (optional)

Don't know, any ideas? :)

## InstaPy configuration

Latest release 0.6.10, unfollow is working fine, just not working with profiles without photos uploaded.

**Comment by zap-wizard** [comment] 2020-08-02 09:37
Same problem here, however, I think I managed to come up with a fix! I'll try to explain the problem:

**THE PROBLEM**
In `unfollow_util.py` a function called `get_following_status` is defined.
In that function the following status is checked with the following code:
```
try:
  browser.find_element_by_xpath(
    read_xpath(get_following_status.__name__, "follow_button_XP")
  )
  follow_button_XP = read_xpath(get_following_status.__name__, "follow_button_XP")
except NoSuchElementException:
  try:
    follow_button = browser.find_element_by_xpath(
      read_xpath(get_following_status.__name__, "follow_span_XP_following")
    )
    return "Following", follow_button
  except:
    return "UNAVAILABLE", None
```
So if the first `try` block didn't raise exceptions, the status is read from the element and returned at the end of the function:
```
following_status = follow_button.text
return following_status, follow_button
```
The `read_xpath` function is defined in the file named `xpath.py`: 
```
from .xpath_compile import xpath

def read_xpath(function_name, xpath_name):
    return xpath[function_name][xpath_name]
```
and gets the xpath from `xpath_compile.py` file:
```
xpath = {}
```
```
xpath["get_following_status"] = {
    "follow_button_XP": "//button[text()='Following' or \
                                  text()='Requested' or \
                                  text()='Follow' or \
                                  text()='Follow Back' or \
                                  text()='Unblock']",
    "follow_span_XP_following": "//button/div/span[contains(@aria-label, 'Following')]",
}
```

So first the `get_following_status` function tries to find a element from this xpath `//button[text()='Following' or text()='Requested' or text()='Follow' or text()='Follow Back' or text()='Unblock']` and if it doesn't find an element, it tries to find an element from this xpath `//button/div/span[contains(@aria-label, 'Following')]`

**This is at least the case in Firefox Browser 77.0.1 on my mac ->**
I have done some testing in the Firefox developer's tools, and it seems that profile pages of users I don't follow contain the element found from the first xpath and the profiles of users I follow that HAVE uploaded photos don't, in their profile pages an element is found from the second xpath. 
But here's the catch: as weird as it seems, for some reason the profile pages of users I follow that HAVE NOT uploaded any photos contain an hidden element found from the first xpath with the text 'Follow'. However, because their profile pages also contain the element found from the second xpath, **my suggestion for a fix is to first check the second xpath (**`//button/div/span[contains(@aria-label, 'Following')]`**) and only then the other one.** 

I hope my explanation was understandable...

**MY FIX**
So my fix is to change the part of the code in `get_following_status` mentioned above to this:
```
try:
  follow_button = browser.find_element_by_xpath(
    read_xpath(get_following_status.__name__, "follow_span_XP_following")
  )
  return "Following", follow_button
except NoSuchElementException:
  try:
    browser.find_element_by_xpath(
      read_xpath(get_following_status.__name__, "follow_button_XP")
    )
    follow_button_XP = read_xpath(get_following_status.__name__, "follow_button_XP")
  except:
    return "UNAVAILABLE", None
```

This fixed my InstaPy bot, but I haven't done any more extensive testing...and I don't know if there was a reason for checking the other xpath first.
Maybe a pull request should be created? @timgrossmann @breuerfelix

**Comment by breuerfelix** [comment] 2020-08-03 11:18
It would be awesome if you could open a PR with these changes and also post the explanation there :) maybe you could even show some screenshots from the dev tools! just fast ones with snippet tool so we can check if its the same case in other browsers :) @zap-wizard 

ant BTW thanks for getting into this so quick !

**Comment by zubus** [comment] 2020-08-04 16:48
Thanks!! its working fine

**Comment by breuerfelix** [comment] 2020-08-06 06:25
The issue is still not fixed in master :) PR welcomed with this !

**Comment by zap-wizard** [comment] 2020-08-06 17:46
@breuerfelix I created the PR (#5687) about this a few days ago and the changes are already been merged. Just forgot to mention it here... 😅

**Comment by breuerfelix** [comment] 2020-08-10 08:40
@zap-wizard ouh... so tim was pretty fast in merging :D sorry for that and thanks for the fast reaction :D

**Closed as completed by breuerfelix** 2020-08-10 08:41 UTC
