### ISSUE TITLE
help

### ISSUE THREAD

**Issue by Arucard11** [InstaPy/InstaPy#6207] opened 2021-06-01 17:57 UTC
File "C:\Users\12146\AppData\Local\Programs\Python\Python39\lib\site-packages\instapy\instapy.py", line 1957, in like_by_tags
    inappropriate, user_name, is_video, reason, scope = check_link(
  File "C:\Users\12146\AppData\Local\Programs\Python\Python39\lib\site-packages\instapy\like_util.py", line 633, in check_link
    media = post_page[0]["shortcode_media"]
KeyError: 0

**Comment by schealex** [comment] 2021-06-02 11:18
yo guys please check if that issue already exists before creating a new one. This is duplicate of #6191 and is fixed by PR #6195

**Closed as completed** 2021-06-09 00:23 UTC
