### ISSUE TITLE
KeyError: 'media' in like by tags

### ISSUE THREAD

**Issue by lucasaraujoo** [InstaPy/InstaPy#4949] opened 2019-08-26 19:12 UTC
i get this error in like by tags

..........................................................................
INFO [2019-08-26 15:59:16] [jamilecastilhomakeup]  Logged in successfully!
''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''
INFO [2019-08-26 15:59:17] [jamilecastilhomakeup]  Saving account progress...
INFO [2019-08-26 15:59:24] [jamilecastilhomakeup]  Tag [1/1]
INFO [2019-08-26 15:59:25] [jamilecastilhomakeup]  --> b'maquiagem'
INFO [2019-08-26 15:59:43] [jamilecastilhomakeup]  desired amount: 45  |  top posts [disabled]: 9  |  possible posts: 14167547
INFO [2019-08-26 16:00:04] [jamilecastilhomakeup]  Like# [1/45]
INFO [2019-08-26 16:00:05] [jamilecastilhomakeup]  https://www.instagram.com/p/B1m5zDpJW_H/

INFO [2019-08-26 16:00:12] [jamilecastilhomakeup]  Sessional Live Report:
        |> No any statistics to show

On session start was FOLLOWING 474 users & had 438 FOLLOWERS
[Session lasted 1.84 minutes]

OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO
INFO [2019-08-26 16:00:13] [jamilecastilhomakeup]  Session ended!
ooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooo

Traceback (most recent call last):
  File "bot.py", line 143, in <module>
    getattr(session, job['functionName'])(**arguments)
  File "C:\Users\Lucas\Desktop\instapygui\env\lib\site-packages\instapy\instapy.py", line 1908, in like_by_tags
    self.logger)
  File "C:\Users\Lucas\Desktop\instapygui\env\lib\site-packages\instapy\like_util.py", line 590, in check_link
    media = post_page[0]['media']
KeyError: 'media'

**Comment by yapizza** [comment] 2019-08-27 09:48
Duplicate of #4882 
[https://github.com/timgrossmann/InstaPy/pull/4918](url)

**Closed as completed** 2019-10-03 11:03 UTC
Labels: wontfix
