### ISSUE TITLE
Image is liked, but when commenting, the code ends

### ISSUE THREAD

**Issue by madebybav** [InstaPy/InstaPy#287] opened 2017-05-29 22:26 UTC
When I run the code, it likes the image, but then when it comes to commenting, there is an error and the code ends.

This is the error:
Traceback (most recent call last):
  File "quickstart.py", line 7, in <module>
    .like_by_tags(['isetups'], amount=30) \
  File "C:\Users\Bav\Downloads\InstaPy-master\instapy\instapy.py", line 415, in like_by_tags
    commented += comment_image(self.browser, comments)
  File "C:\Users\Bav\Downloads\InstaPy-master\instapy\comment_util.py", line 17, in comment_image
    browser.execute_script("arguments[0].value = '" + rand_comment + " ';", comment_input[0]);
IndexError: list index out of range

**Comment by timgrossmann** [comment] 2017-05-30 04:58
@atomhax

**Comment by atomhax** [comment] 2017-05-30 16:10
@timgrossmann I'll get to this sometime today. To me... the error  "IndexError: list index out of range" is referring to the comment_input array being empty. I bet a simple try-catch-exception block is exactly what we need here. I could be wrong.

**Comment by MichaelZhou1998** [comment] 2017-05-30 16:39
I am also having this exact same issue. (on Windows)

**Comment by andreroggeri** [comment] 2017-05-30 22:26
It seems that the comment has changed from `input` to `textarea`

**Comment by andreroggeri** [comment] 2017-05-30 22:29
I'm modifying the following line of `comment_util.py`

```
comment_input = browser.find_elements_by_xpath('//input[@placeholder = "Add a comment…"]')
```

To

```
comment_input = browser.find_elements_by_xpath('//textarea[@placeholder = "Add a comment…"]')
```

**Comment by atomhax** [comment] 2017-05-30 22:30
It's still input for me. I seem to remember that they roll out UI features
to user accounts slowly. We may have to support both versions for a while.

**Comment by atomhax** [comment] 2017-05-30 22:40
@andreroggeri we need something like what they did during the graphql changes. You can acutally see an example of it in the live code in the like_util. 

But I digress.. what we need is like this I think: 

```
comment_input = browser.find_elements_by_xpath('//input[@placeholder = "Add a comment…"]')
if comment_input:
 #if comment_input is the old way do stuff
else:
  comment_input = browser.find_elements_by_xpath('//textarea[@placeholder = "Add a comment…"]')
  #it's the new way do more stuff

```

**Comment by andreroggeri** [comment] 2017-05-30 22:42
Ok, I can make a PR.

But I'm getting another error:

```
Traceback (most recent call last):
  File "C:\Program Files\JetBrains\PyCharm 2017.1.1\helpers\pydev\pydevd.py", line 1585, in <module>
    globals = debugger.run(setup['file'], None, None, is_module)
  File "C:\Program Files\JetBrains\PyCharm 2017.1.1\helpers\pydev\pydevd.py", line 1015, in run
    pydev_imports.execfile(file, globals, locals)  # execute the script
  File "C:\Program Files\JetBrains\PyCharm 2017.1.1\helpers\pydev\_pydev_imps\_pydev_execfile.py", line 18, in execfile
    exec(compile(contents+"\n", file, 'exec'), glob, loc)
  File "E:/Projetos/InstaPy/quickstart.py", line 19, in <module>
    .like_by_tags(like_tags, amount=100) \
  File "E:/Projetos/InstaPy\instapy\instapy.py", line 415, in like_by_tags
    commented += comment_image(self.browser, comments)
  File "E:/Projetos/InstaPy\instapy\comment_util.py", line 22, in comment_image
    print("--> Commented: " + rand_comment.encode('utf-8'))
TypeError: Can't convert 'bytes' object to str implicitly
```

Is not possible to concatenate a string with bytes

**Comment by atomhax** [comment] 2017-05-30 22:46
Whats your Python version? I just read it can make a difference how this case is handled. I ask because this line of code works fine on my Linux and MacOS builds.

**Comment by john-crossley** [comment] 2017-05-30 22:47
I'm also having this issue on Mac OS X `Python 2.7.13` I literally know no python so looks like i'm gonna have to learn 🤣

**Comment by andreroggeri** [comment] 2017-05-30 22:48
@atomhax  I'm on 3.5.1 (But also checked on 3.6.1) runnin on Windows 10

**Comment by andreroggeri** [comment] 2017-05-30 22:49
```
Python 3.6.1 (v3.6.1:69c0db5, Mar 21 2017, 17:54:52) [MSC v.1900 32 bit (Intel)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> encoded = 'Encode this'.encode('utf-8')
>>> print('Hey...')
Hey...
>>> print('Hey...' + encoded)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: must be str, not bytes
>>>
```

**Comment by andreroggeri** [comment] 2017-05-30 22:51
Changing to `print("--> Commented: {}".format(rand_comment.encode('utf-8')))` fixes.

I can make the PR, but will conflict with yours #288 .

So, maybe its better to make this change on your PR. What do you think about it ?

**Comment by atomhax** [comment] 2017-05-30 22:52
Ok. I'll make the change. 2 seconds. I want to make sure to test it first. I'm sure this is causing a lot of people a headache today.

**Comment by andreroggeri** [comment] 2017-05-30 22:58
Great ! 😄 

Some tests would be great for preventing regressions, but I didn't find any. 😢

**Comment by atomhax** [comment] 2017-05-30 23:26
Yeah some tests are a great idea!! 👍 

If you have experience writing regression tests feel free to dive in. I put that PR up. I tested it on my insta and it worked fine.

**Comment by atomhax** [comment] 2017-05-31 20:51
@madebybav @timgrossmann I believe PR #288 addressed this issue. Can we close it?

**Closed as completed** 2017-06-01 07:16 UTC
Labels: bug, help wanted
