### ISSUE TITLE
Bot won't even startup anymore! would love any help <3

### ISSUE THREAD

**Issue by supmag** [InstaPy/InstaPy#1937] opened 2018-05-01 22:44 UTC
## Expected Behavior
It normaly works fine even though it would randomly give an error
## Current Behavior
Doesnt even startup
## InstaPy configuration
Error: INFO [2018-05-02 00:42:19] [ehsen.sonny] Session started - 2018-05-02 00:42:19
 WARNING [2018-05-02 00:42:19] [ehsen.sonny] Sorry, Record Activity is not working on Windows. We're working to fix this soon!
 INFO [2018-05-02 00:42:47] [ehsen.sonny] Logged in successfully!
 Traceback (most recent call last):
 File "quickstart.py", line 5, in <module>
 session.login()
 File "D:\2016 main fodlers\My documents\GitHub\InstaPy\instapy\instapy.py", line 317, in login
 self.followed_by = log_follower_num(self.browser, self.username, self.logfolder)
 File "D:\2016 main fodlers\My documents\GitHub\InstaPy\instapy\print_log_writer.py", line 11, in log_follower_num
 "return window._sharedData.""entry_data.ProfilePage[0]."
 File "C:\Users\Ehsen\AppData\Local\Programs\Python\Python36-32\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 543, in execute_script
 'args': converted_args})['value']
 File "C:\Users\Ehsen\AppData\Local\Programs\Python\Python36-32\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 308, in execute
 self.error_handler.check_response(response)
 File "C:\Users\Ehsen\AppData\Local\Programs\Python\Python36-32\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 194, in check_response
 raise exception_class(message, screen, stacktrace)
 selenium.common.exceptions.WebDriverException: Message: unknown error: Cannot read property 'graphql' of undefined
 (Session info: chrome=66.0.3359.139)
 (Driver info: chromedriver=2.38.552522 (437e6fbedfa8762dec75e2c5b3ddb86763dc9dcb),platform=Windows NT 6.1.7601 SP1 x86_64)

**Comment by craigricker** [comment] 2018-05-01 22:52
Duplicate of #1936 

@supmag I think this is effecting a lot of users, hopefully there will be a fix soon!

**Closed as completed** 2018-05-01 22:57 UTC
