### ISSUE TITLE
Says image was liked but doesn't actually like it

### ISSUE THREAD

**Issue by anthonyattard** [InstaPy/InstaPy#1467] opened 2018-02-19 19:52 UTC
When I run this on my Digital Ocean server the script says everything is working properly and that images have been liked but it doesn't actually like the post. The script works fine on my MacOS local but not on the Ubuntu server. 

Any ideas?

**Comment by sionking** [comment] 2018-02-20 08:44
I heard Digital Ocean have bot blocks.

**Comment by sionking** [comment] 2018-02-20 08:45
Also there is new method I need to PR that every N likes do reload to page to see if really liked.

**Comment by anthonyattard** [comment] 2018-02-21 00:34
@sionking any links to Digital Ocean having bot blocks? Are proxies a good solution to get the bot to work consistently?

**Comment by stainless33** [comment] 2018-02-27 02:00
I'm currently having the same issue when running Ubuntu on Digital Ocean. The likes were working correctly earlier today but they have since ceased. The script indicates that the images have been liked, but when I check my Instagram account to view recently liked images, they aren't present.

Following, unfollowing and commenting work absolutely fine.

**Comment by stainless33** [comment] 2018-02-28 01:52
@anthonyattard In your quickstart.py make sure that your InstaPy session is using `headless_browser=True`

```
 session = InstaPy(username=insta_username,
                      password=insta_password,
                      headless_browser=True,
                      multi_logs=True,nogui=True)
    session.login()
```
I was running it successfully with `headless_browser=False` on Ubuntu server for a few days until it stopped working. Changing it to 'True' resolved my issue.

**Comment by CharlesCCC** [comment] 2018-02-28 18:13
I'm having the some issue from time to time

I saw this log
```
2018-02-28 13:01:38 - INFO - [3/14]
2018-02-28 13:01:38 - INFO - https://www.instagram.com/p/Bfv-b0LFrt9/?tagged=aerialphotography
2018-02-28 13:01:41 - INFO - Image from: b'angelovalentinoromano'
2018-02-28 13:01:45 - INFO - Number of Followers: 414
2018-02-28 13:01:45 - INFO - Link: b'https://www.instagram.com/p/Bfv-b0LFrt9/?tagged=aerialphotography'
2018-02-28 13:01:45 - INFO - Description: b'Spina dorsale #landscape #landscapephotography #city #cityscape #aerialphotography #art #architecture #architecturephotography #artphotography #igers #igersfoggia #volgofoggia #yallersitalia #picoftheday #photooftheday #photography #beautiful #beauty #nofilter #tagamo #instagood #instagram #instagreat #weareinpuglia #visitpuglia'
2018-02-28 13:01:58 - INFO - --> Image Liked!
2018-02-28 13:02:00 - INFO - --> Commented: b'What a great shot!!'
2018-02-28 13:02:01 - INFO - --> Not following
```
but when I check the actual image, it didn't liked, it only get comment. 
i already have the headless set to True.

**Comment by stainless33** [comment] 2018-03-01 04:39
@CharlesCCC Are you finding that it's a sporadic occurrence? Mine has also stopped working again even though it was working properly previously.

**Comment by CharlesCCC** [comment] 2018-03-01 13:43
@stainless33 yes, sporadic, I have opened a new issue here [1519](https://github.com/timgrossmann/InstaPy/issues/1519) 
Looks like @sionking already have a solution for it.

**Comment by CharlesCCC** [comment] 2018-03-01 16:00
Guys, I confirmed my setting was too aggressive.  Make sure never like more than 100 per hour and like more than 2400 per day. When I think about it, it only 1440 minutes per day. no human being is capable like 2400+ pic per day 24X7... it just not realistic. 

This issue should be closed as [1519](https://github.com/timgrossmann/InstaPy/issues/1519)

@stainless33 @anthonyattard make sure you set a longer interval and less likes per run.

**Closed as completed** 2018-11-23 12:06 UTC
Labels: wontfix
